name: Build and Deploy Container AWS ECS

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      github_sha:
        required: true
        type: string
      region:
        required: true
        type: string
      account:
        required: true
        type: string
      oidc_role:
        required: true
        type: string
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      config_path:
        required: true
        type: string
    secrets:
      BUILD_SERVER_SSH_KEY:
        required: true
      GCP_CREDENTIALS_JSON:
        required: true

jobs:
  build_publish_deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.2 # Add ssh-agent
        with:
          ssh-private-key: |
            ${{ secrets.BUILD_SERVER_SSH_KEY }}

      # Setup gcloud CLI
      - name: Get GCP secrets
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"
          export_environment_variables: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.oidc_role }}
          aws-region: ${{ inputs.region }}

      - name: Install AWS Copilot CLI
        uses: ksivamuthu/aws-copilot-github-action@v0.0.1
        with:
          command: install

      # Build the Docker image
      - id: docker
        name: Build and push docker image
        env:
          PROJECT_ID: ${{ inputs.gcp_project_id }}
          GITHUB_SHA: ${{ inputs.github_sha }}
          REGION: ${{ inputs.region }}
          ACCOUNT: ${{ inputs.account }}
          APP_NAME: ${{ inputs.app_name }}
          SERVICE: ${{ inputs.service }}
          ENVIRONMENT: ${{ inputs.environment }}
          CONFIG_PATH: ${{ inputs.config_path }}
        run: |
          export AWS_REGION=$REGION

          DB_SECRET_FULL_ARN=$(aws secretsmanager list-secrets --filter Key="tag-key",Values="aws:cloudformation:stack-name" Key="tag-value",Values="OmcareCloudDB" | jq -r '.SecretList[0].ARN')
          DB_SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_FULL_ARN | jq -r '.SecretString')
          PG_HOST=$(echo $DB_SECRET_VALUE | jq -r '.host')

          sed -e "s|#PGHOST|$PG_HOST|g" $CONFIG_PATH >> "$CONFIG_PATH.temp"
          cp "$CONFIG_PATH.temp" $CONFIG_PATH
          rm "$CONFIG_PATH.temp"

          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
          
          gcloud auth application-default print-access-token > auth.txt
          DOCKER_BUILDKIT=1 docker build --build-arg GCP_PROJECT_ID=$PROJECT_ID --build-arg ENVIRONMENT=$ENVIRONMENT --secret id=auth,src=auth.txt -t $SERVICE --ssh default .

          docker tag $SERVICE $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$APP_NAME/$SERVICE:latest
          docker tag $SERVICE $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$APP_NAME/$SERVICE:$GITHUB_SHA
          
          docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$APP_NAME/$SERVICE:latest
          docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$APP_NAME/$SERVICE:$GITHUB_SHA

          ENV_SHOW_RESOURCES=$(copilot env show --name $ENVIRONMENT --app $APP_NAME --json --resources)
          ENV_CLUSTER=$(echo $ENV_SHOW_RESOURCES | jq -r '.resources[] | select((.logicalID == "Cluster")) | .physicalID')

          SVC_SHOW_RESOURCES=$(copilot svc show --name $SERVICE --app $APP_NAME --json --resources)
          SERVICE_ARN=$(echo $SVC_SHOW_RESOURCES | jq -r '.resources | .["'${ENVIRONMENT}'"][] | select((.logicalID == "Service")) | .physicalID')
          SERVICE_ARN_ARR=(${SERVICE_ARN//// })
          SERVICE_NAME=${SERVICE_ARN_ARR[2]}

          aws ecs update-service \
              --service "$SERVICE_NAME" \
              --cluster "$ENV_CLUSTER" \
              --force-new-deployment

          aws ecs tag-resource --resource-arn $SERVICE_ARN --tags key=source/revision,value=$GITHUB_SHA

