name: Deploy Omcare Cloud IaC to AWS

on:
  workflow_call:
    inputs:
      github_sha:
        required: true
        type: string
      region:
        required: true
        type: string
      account:
        required: true
        type: string
      oidc_role:
        required: true
        type: string
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.oidc_role }}
          aws-region: ${{ inputs.region }}
      
      - name: Install AWS Copilot CLI
        uses: ksivamuthu/aws-copilot-github-action@v0.0.1
        with:
          command: install
      
      - name: Execute Copilot Deployment Script
        env:
          GITHUB_SHA: ${{ inputs.github_sha }}
          REGION: ${{ inputs.region }}
          ACCOUNT: ${{ inputs.account }}
          APP_NAME: ${{ inputs.app_name }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          copilot --version
          ./scripts/copilot-deploy.sh

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Deploy OmcareCloud CDK App
        env:
          CDK_DEFAULT_REGION: ${{ inputs.region }}
          CDK_DEFAULT_ACCOUNT: ${{ inputs.account }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          cd omcare-cloud-cdk
          npm i
          npm run cdk synth
          npm run cdk deploy --require-approval=never -c environment=$ENVIRONMENT

