on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      oidc_role:
        required: true
        type: string
    secrets:
      # BUILD_SERVER_SSH_KEY:
      #   required: true
      GCP_CREDENTIALS_JSON:
        required: true

jobs:
  create-cert:
    name: Generate Cert
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - uses: webfactory/ssh-agent@v0.5.2 # Add ssh-agent
      #   with:
      #     ssh-private-key: |
      #       ${{ secrets.BUILD_SERVER_SSH_KEY }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.oidc_role }}
          aws-region: ${{ inputs.region }}

      # Setup gcloud CLI
      - name: Get GCP secrets
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"
          export_environment_variables: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: "Install Certbot Libraries"
        run: |
          python3 --version
          pip3 --version
          pip3 install certbot certbot-dns-route53
          certbot --version
      
      - name: "Generate / Renew Cert"
        run: |
          aws sts get-caller-identity
          sudo /opt/hostedtoolcache/Python/3.10.12/x64/bin/certbot certonly --dns-route53 -d '*.om.care','*.internal.om.care' -v --keep-until-expiring -m developer@omcare.co --agree-tos --non-interactive


